### ISSUE TITLE
Move content storeage to OpenStack.

### ISSUE THREAD

**Issue by hakan-liden** [blinfo/NavetFile#8]
- [x] Create Account on Elastx
- [x] Change handling of Content in core 
- [x] Change SaveFileCommand to persist content on os
- [x] Change GetFileContentCommand to fetch content from os
- [x] Change DeleteFileCommand to delete from os as well
- [x] Change AnyFilesCommand to check for FileMeta (or content on os)
- [x] Create processor to move data from mysql to os 
- [x] Backup data from db including content
- [ ] Backup data from os including content
- [ ] Restore from backup 
- - [x] Separate restore for each area 
- - [ ] Bulk restore for all areas 
- [ ] Write tests to ensure API is unchanged 
- [ ] Write tests to ensure no loss when transfer is done 
- [ ] Handle Roll-Back

**Comment by xperjon** [comment]
Nice!

**Comment by hakan-liden** [comment]
List of features moved to JIRA
